app/Http/routes.php
        'uses' => 'Auth\AuthController@getLogin',
    ]);

    Route::post('login', [
        'as' => 'login-post',
        'uses' => 'Auth\AuthController@postLogin',
    ]);

    // Registration routes...
    Route::get('register', [
        'as' => 'register',
        'uses' => 'Auth\AuthController@getRegister',
    ]);

    Route::post('register', [
        'as' => 'register-post',
        'uses' => 'Auth\AuthController@postRegister',
    ]);

    // Password REMIND
    Route::get('password/remind', [
        'as' => 'password-remind',
        'uses' => 'Auth\PasswordController@getPasswordRemind',
    ]);

    Route::post('password/remind', [
        'as' => 'password-remind-post',
        'uses' => 'Auth\PasswordController@postPasswordRemind',
    ]);

    // Password REMIND - RESET
    Route::get('password/reset/{token}', [
        'as' => 'password-reset',
        'uses' => 'Auth\PasswordController@getResetPassword'
    ]);

    Route::get('password/reset', function () {
        return redirect()->route('password-reset');
    });

    Route::post('password/reset', [
        'as' => 'password-reset-post',
        'uses' => 'Auth\PasswordController@postResetPassword',
    ]);

});

/*===========================================================
  NOT FILTER
===========================================================*/
// Home page
Route::get('/', [
    'as' => 'home',
    'uses' => 'PagesController@index',
]);

//Logout
Route::get('logout', [
    'as' => 'logout',
    'uses' => 'Auth\AuthController@getLogout',
]);

//Change Language
Route::get('language/{lang}', [
    'as' => 'lang-select',
    'uses' => 'LanguageController@setLanguage',
]);

//NOT Confirm Register
Route::get('register/problem', [
    'as' => 'registration-no-confirm',
    'uses' => 'Auth\AuthController@getRegisterNotConfirm',
]);

Route::post('register/problem', [
    'as' => 'registration-no-confirm-post',
    'uses' => 'Auth\AuthController@postRegisterNotConfirm',
]);

//Register Complete
Route::get('register/complete', [
    'as' => 'registration-complete',
    'uses' => 'Auth\AuthController@registerComplete',
]);

//Confirm Register
Route::get('register/confirm/{token}', [
    'as' => 'register-confirm-email',
    'uses' => 'Auth\AuthController@registerConfirm',
]);

Route::group(['prefix' => 'ads'], function () {

    //Ads
    Route::get('new', [
        'as' => 'ads-new-offer',
        'uses' => 'AdsController@adsNewOffer',
    ]);

    Route::get('search', [
        'as' => 'ads-new-need',
        'uses' => 'AdsController@newNeedRoom',
    ]);

    Route::get('offer/finish', [
        'as' => 'ads-offer-finish',
        'uses' => 'AdsController@adsOfferFinishGroupOne',
    ]);

});

Route::get('offer/{offer_id}', [
    'as' => 'offer-watch-open',
    'uses' => 'AdsController@getAdOfferWatch',
]);

Route::get('user/{id}/account', [
    'as' => 'user-profile',
    'uses' => 'AccountController@userProfile',
]);

Route::get('user/{id}/ads', [
    'as' => 'user-profile-ads',
    'uses' => 'AccountController@userAds',
]);

//VIP && SHOP
Route::get('shop', [
    'as' => 'shop-page',
    'uses' => 'ShopController@getAboutShop',
]);

//SUPPORT
Route::group(['prefix' => 'support'], function () {

    Route::get('', function(){
        return redirect()->route('faq-login-password');
    });

    Route::post('new-dialog', [
        'as' => 'post-support-dialog',
        'uses' => 'SupportController@postNewSupportDialog',
    ]);

    Route::group(['prefix' => 'rules'], function () {

        Route::get('', function(){
            return redirect()->route('rules-general');
        });

        Route::get('general', [
            'as' => 'rules-general',
            'uses' => 'SupportController@rulesGeneral',
        ]);

        Route::get('ads-placing', [
            'as' => 'rules-terms-placing',
            'uses' => 'SupportController@rulesTermsPlacing',
        ]);

        Route::get('ads-requirements', [
            'as' => 'rules-ads-requirements',
            'uses' => 'SupportController@rulesAdsRequirements',
        ]);

        Route::get('paid-services', [
            'as' => 'rules-paid-services',
            'uses' => 'SupportController@rulesPaidServices',
        ]);

    });

    Route::group(['prefix' => 'faq'], function () {

        Route::get('', function(){
            return redirect()->route('faq-login-password');
        });

        Route::get('login-password', [
            'as' => 'faq-login-password',
            'uses' => 'SupportController@faqLoginAndPassword',
        ]);

        Route::get('ads-work', [
            'as' => 'faq-ads-work',
            'uses' => 'SupportController@faqAdsWork',
        ]);

        Route::get('placing-ads', [
            'as' => 'faq-placing-ads',
            'uses' => 'SupportController@faqPlacingAds',
        ]);

        Route::get('ad-edit', [
            'as' => 'faq-ad-edit',
            'uses' => 'SupportController@faqAdEdit',
        ]);

    });

});

/*===========================================================
  AJAX
===========================================================*/
Route::group(['middleware' => 'ajax'], function () {

    Route::post(
        'ads/offer/images',
        'FilesController@adsOfferImages'
    );

    Route::post(
        'ads/edit/images',
        'FilesController@adsOfferEditImages'
    );

    Route::post(
        'ads/delete-image',
        'FilesController@deleteImageAjax'
    );

    Route::post('ads/new/offerForm', [
        'uses' => 'AdsController@postAdsNewOffer',
    ]);

    Route::post('ads/edit/form', [
        'uses' => 'AdsController@adsEditAjax',
    ]);

    Route::get(
        'ads/cities',
        'AdsController@getCitiesForAds'
    );

    Route::post(
        'ads/need/search',
        'AdsController@AddNeedSearchAjax'
    );

    Route::post(
        'ads/add-bookmark',
        'AdsController@AddToBookmark'
    );

    Route::post(
        'ads/delete-one-bookmark',
        'AdsController@DeleteOneBookmark'
    );

    Route::post(
        'ads/delete-all-bookmarks',
        'AdsController@DeleteAllBookmarks'
    );

    Route::post(
        'account/ads/up',
        'AdsController@adUpFreeAjax'
    );
    Route::post(
        'account/ads/up-premium',
        'AdsController@adUpPremiumAjax'
    );

    Route::post(
        'account/ads/show-hide',
        'AdsController@adHideOrShowStatusAjax'
    );

    Route::post('ads/add-privileges', [
        'uses' => 'ShopController@postAddPrivilege',
    ]);

    Route::post('notification/hide', [
        'uses' => 'PagesController@hideNotification',
    ]);

    Route::post('notification/hide/all', [
        'uses' => 'PagesController@hideAllNotifications',
    ]);

    Route::post('account/avatar/upload-temp', [
        'uses' => 'FilesController@avatarForTempFolder',
    ]);

    Route::post('account/avatar/upload', [
        'uses' => 'FilesController@avatarUploadAjax',
    ]);

    Route::post('account/avatar/delete', [
        'uses' => 'FilesController@avatarDeleteAjax',
    ]);

    Route::post('ads/image/cover-edit', [
        'uses' => 'AdsController@adCoverImageNameById',
    ]);

    Route::post('ads/image/cover-crop', [
        'uses' => 'FilesController@adCoverImageCrop',
    ]);

});

/*===========================================================
  ADMINISTRATION
===========================================================*/
Route::group(['prefix' => 'admin'], function () {

    Route::group(['middleware' => 'admin'], function () {

        Route::get('', [
            'as' => 'admin-general',
            'uses' => 'AdminController@getAdminGeneral',
        ]);

        Route::get('support', [
            'as' => 'admin-support',
            'uses' => 'AdminController@getAdminSupport',
        ]);

        Route::get('support/{dialog_id}', [
            'as' => 'admin-support-answer',
            'uses' => 'AdminController@adminSupportAnswer',
        ]);

        Route::post('support/answer', [
            'as' => 'post-admin-support-answer',
            'uses' => 'AdminController@postAdminSupportAnswer',
        ]);

        Route::get('find/user', [
            'uses' => 'AdminController@findUserSelect2Ajax',
        ]);

        Route::get('ads', [
            'as' => 'admin-ads',
            'uses' => 'AdminController@getAdsValidate',
        ]);

    });

    Route::group(['middleware' => 'super-admin'], function () {

        Route::get('notification/create', [
            'as' => 'admin-notification',
            'uses' => 'AdminController@getNotificationPage',
        ]);

        Route::post('notification/create/new', [
            'as' => 'admin-notification-post',
            'uses' => 'AdminController@createNewNotificationPost',
        ]);

        Route::post('notification/delete', [
            'uses' => 'AdminController@deleteGeneralNotificationAjax',
        ]);

        Route::get('gift/create', [
            'as' => 'admin-gift',
            'uses' => 'AdminController@makeGiftAction',
        ]);

        Route::post('gift/create/general', [
            'as' => 'admin-gift-general',
            'uses' => 'AdminController@giveGeneralGiftPost',
        ]);

        Route::post('gift/create/personal', [
            'as' => 'admin-gift-personal',
            'uses' => 'AdminController@givePersonalGiftPost',
        ]);

        Route::post('ad/delete', [
            'uses' => 'AdminController@deleteAdAjax',
        ]);

        Route::get('shop', [
            'as' => 'admin-shop',
            'uses' => 'AdminController@getShop',
        ]);

        Route::post('shop/update/service', [
            'uses' => 'AdminController@shopUpdateService',
        ]);

        Route::post('shop/update/package/{name}', [
            'as' => 'admin-shop-package-update',
            'uses' => 'AdminController@shopUpdatePackage',
        ]);

        Route::post('shop/update/colors', [
            'uses' => 'AdminController@updateColorsAjax',
        ]);

    });

app/Models/SxgeoCity.php
<?php namespace App\Models;

use App\Http\MyClass\LocationClass;
use Illuminate\Database\Eloquent\Model;
use DB;
use Request;

class SxgeoCity extends Model
{


    protected $table = 'sxgeo_cities';


    public function getRegion()
    {
        return $this->hasOne('\App\Models\SxgeoRegion', 'id', 'region_id');
    }


    public static function searchCities($query, $locale)
    {
        $result = SxgeoCity::where('name_' . $locale, 'LIKE', $query . '%')
            ->select('id')
            ->take(10)
            ->get();

        return $result;
    }


    public static function getCityRegionCountryById($cities, $locale)
    {
        $results = SxgeoCity::whereIn('id', $cities)
            ->with('getRegion.getCountry')
            ->take(10)
            ->get();

        foreach ($results as $result) {

            $popularCities[] = [

                'id' => $result['id'],
                'text' => $result['name_' . $locale],
                'country' => $result['getRegion']['getCountry']['name_' . $locale]

            ];

        }
        return isset($popularCities) ? $popularCities : null;
    }


    public static function getUserLocationCityRegionCountry($city)
    {
        $city = $city ? $city : '524901';

        $userCity = SxgeoCity::where('id', $city)
            ->select('id', 'name_' . userLocale() . ' as text')
            ->first();

        return $userCity;
    }


    public static function getCityNameById($cityId, $locale)
    {
        $cityName = SxgeoCity::where('id', $cityId)->pluck('name_' . $locale);

        return $cityName;
    }


    public static function getCitiesByRegionId($region_id)
    {
        userLocale() == 'ru' ?
            $cities = SxgeoCity::where('region_id', $region_id)
                ->orderBy('name_ru', 'asc')
                ->select('id', 'name_ru as name')
                ->get() :
            $cities = SxgeoCity::where('region_id', $region_id)
                ->orderBy('name_en', 'asc')
                ->select('id', 'name_en as name')
                ->get();

        return $cities;
    }


}

resources/views/rules/ads-requirements.blade.php
@extends('rules.main')
@section('body')

    <h2 class="support-title">{{ trans('rules.ads-requirements.title') }}</h2>

    <div>
        {!! trans('rules.ads-requirements.foreword') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.relevance.title') }}</h3>
        {!! trans('rules.ads-requirements.relevance.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.unique.title') }}</h3>
        {!! trans('rules.ads-requirements.unique.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.region.title') }}</h3>
        {!! trans('rules.ads-requirements.region.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.details.title') }}</h3>
        {!! trans('rules.ads-requirements.details.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.price.title') }}</h3>
        {!! trans('rules.ads-requirements.price.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.photos.title') }}</h3>
        {!! trans('rules.ads-requirements.photos.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.ads-requirements.third-person.title') }}</h3>
        {!! trans('rules.ads-requirements.third-person.text') !!}
    </div>

@endsection


@section('js-bottom')

@endsection

resources/views/rules/general.blade.php
@extends('rules.main')
@section('body')

    <h2 class="support-title">{{ trans('rules.general.title') }}</h2>

    <div>
        {!! trans('rules.general.foreword') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.terms.title') }}</h3>
        {!! trans('rules.general.terms.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.conditions.title') }}</h3>
        {!! trans('rules.general.conditions.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.register.title') }}</h3>
        {!! trans('rules.general.register.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.ads.title') }}</h3>
        {!! trans('rules.general.ads.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.liability.title') }}</h3>
        {!! trans('rules.general.liability.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.information.title') }}</h3>
        {!! trans('rules.general.information.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.intellectual.title') }}</h3>
        {!! trans('rules.general.intellectual.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.use-information.title') }}</h3>
        {!! trans('rules.general.use-information.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.messages.title') }}</h3>
        {!! trans('rules.general.messages.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.validity.title') }}</h3>
        {!! trans('rules.general.validity.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.assignment.title') }}</h3>
        {!! trans('rules.general.assignment.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.general.disputes.title') }}</h3>
        {!! trans('rules.general.disputes.text') !!}
    </div>

@endsection


@section('js-bottom')

@endsection

resources/views/rules/main.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>

    @include('partials.meta')

    <title>{{ $title or '' }} | {{ config('app.site_name') }}</title>

    @include('partials.packages-css')

    <script src="/myjs/support.js"></script>

    <link href='/css/melito_css/support.css' rel='stylesheet' type='text/css'>

</head>
<body>

@include('partials.alert-top')

<div class="container-fluid all-home-tmp">

    <div class="row row-header">
        <div class="col-md-24 section-header">
            @include('partials.header')
        </div>
    </div>

    <div class="row row-center faq-rules-menu-row general-menu-collapse-1">
        <div class="col-xs-24 col-sm-7 col-md-6 col-lg-6">
            <nav class="navbar">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        @include('rules.menu')
                    </div>
                </div>
            </nav>
        </div>
        <div class="col-xs-24 col-sm-15 col-md-15 col-lg-14">
            @include('partials.page-notification')
            @yield('body')
            @include('partials.packages-js')
            @yield('js-bottom')
            @include('modals.support-send-message')
        </div>
    </div>

    <div class="row row-footer">
        <div class="col-md-24 section-footer">
            @include('partials.footer')
        </div>
    </div>

</div>

</body>
</html>

resources/views/rules/menu.blade.php
<div class="list-group">

    <a class="list-group-item @if($menuActive == 'general') active @endif" href="{{ route('rules-general') }}">
        {{ trans('rules.menu.general') }}
    </a>

    <a class="list-group-item @if($menuActive == 'terms-placing') active @endif" href="{{ route('rules-terms-placing') }}">
        {{ trans('rules.menu.terms-placing') }}
    </a>

    <a class="list-group-item @if($menuActive == 'ads-requirements') active @endif" href="{{ route('rules-ads-requirements') }}">
        {{ trans('rules.menu.ads-requirements') }}
    </a>

    <a class="list-group-item @if($menuActive == 'paid-services') active @endif" href="{{ route('rules-paid-services') }}">
        {{ trans('rules.menu.paid-services') }}
    </a>

</div>

<div class="list-group second-menu">

    <a class="list-group-item" data-toggle="modal" data-target="#modalSupportSendMessage">
        {{ trans('home.menu.support') }}
    </a>

    <a class="list-group-item" href="{{ route('faq-login-password') }}">
        {{ trans('home.menu.faq') }}
    </a>

</div>

resources/views/rules/paid-services.blade.php
@extends('rules.main')
@section('body')

    <h2 class="support-title">{{ trans('rules.paid-services.title') }}</h2>

    <div>
        {!! trans('rules.paid-services.foreword') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.terms.title') }}</h3>
        {!! trans('rules.paid-services.terms.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.general.title') }}</h3>
        {!! trans('rules.paid-services.general.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.obligations.title') }}</h3>
        {!! trans('rules.paid-services.obligations.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.settlement.title') }}</h3>
        {!! trans('rules.paid-services.settlement.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.responsibility.title') }}</h3>
        {!! trans('rules.paid-services.responsibility.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.claims.title') }}</h3>
        {!! trans('rules.paid-services.claims.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.paid-services.agreement.title') }}</h3>
        {!! trans('rules.paid-services.agreement.text') !!}
    </div>

@endsection


@section('js-bottom')

@endsection

resources/views/rules/terms-placing.blade.php
@extends('rules.main')
@section('body')

    <h2 class="support-title">{{ trans('rules.terms-placing.title') }}</h2>

    <div>
        {!! trans('rules.terms-placing.foreword') !!}
    </div>

    <div>
        <h3>{{ trans('rules.terms-placing.provisions.title') }}</h3>
        {!! trans('rules.terms-placing.provisions.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.terms-placing.user-obligations.title') }}</h3>
        {!! trans('rules.terms-placing.user-obligations.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.terms-placing.provide-information.title') }}</h3>
        {!! trans('rules.terms-placing.provide-information.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.terms-placing.compliance.title') }}</h3>
        {!! trans('rules.terms-placing.compliance.text') !!}
    </div>

    <div>
        <h3>{{ trans('rules.terms-placing.guarantees.title') }}</h3>
        {!! trans('rules.terms-placing.guarantees.text') !!}
    </div>

@endsection


@section('js-bottom')

@endsection